version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: thesis-helper-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - UPLOAD_DIR=/app/uploads
      - MAX_FILE_SIZE_MB=10
      - FILE_RETENTION_HOURS=24
      - ALLOWED_ORIGINS=http://localhost,http://localhost:3000
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - thesis-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: thesis-helper-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - thesis-network

networks:
  thesis-network:
    driver: bridge

volumes:
  uploads:
  logs: